#CREATED BY Absa jay

number =input ("Enter a number:")

if number >0:
    print ("its positive")
elif number >1000:
    print("it is very large number")
else:
    print("it is a negative number")



standard = int (input ("Enter your standard"))


if standard >= 53:
    print("A")
elif standard >=51:
    print("A-")
elif standrad >=49:
   print("B+")
elif standard >=47:
    print("B")
elif standard >=45:
    print("B-")    
elif standard>=43:
    print("C+")
elif Standard >=40:
    print ("c")      
elif standard >=30:
    print(D)
else:
    print("f")